// data/projects.ts — merged from phillipolarte.com and grad portfolio
// Replace image paths with your own. Keep slugs stable.

export type Project = {
  title: string;
  subtitle?: string;
  link?: string;
  img: string;
  tags: string[];
  overview: string;
  role: string;
  outcomes: string[];
  why: string;
  key_components: string[];
  featured?: boolean;
  outcomesVisual?: string;
  outcomesVisual2?: string;
  processVisual?: string;
  overviewVisual?: string;
  featuredVideo?: string;
  architectureDesc?: string;
  teamSize?: string;
  technicalOverview?: string;
  designDesc?: string;
  uxVisual?: string;
  codeSnippet?: {
    language: string; // e.g., "json" or "python"
    code: string;     // The actual prompt or logic snippet
    caption: string;  // e.g., "System Prompt Constraints"
  };
  gallery?: {
    src: string;
    type: 'video' | 'image';
    caption: string;
  }[];
};

export const projects: Record<string, Project> = {
  // --- Flagship / main projects ---
  maia: {
    title: 'The MAIA Experience',
    subtitle: 'Generative Voice & Audio',
    link: 'https://the-maia-experience.framer.ai/',
    img: '/images/maia.png',
    tags: ['GenAI', 'Voice UI', 'Python', 'LLM', 'Latency Masking'],
    overview: `An intimate, 10‑minute encounter with MAIA — a real‑time AI character that sees, listens, and converses with visitors inside "Prof. Dupin’s study" as onboarding to a larger story world. Think AI meets Disney pre‑show experience - personalized for each guest.`,
    role: `MS in Emerging Tech, AI & Design at NYU. Lead Designer & Engineer. End‑to‑end experience design, LLM prompt engineering, real‑time voice interaction system architecture, and front‑end development for the interactive installation.`,
      outcomes: [
      "Engineered a local-LLM mult-threaded architecture that reduced latency from 10s to <200ms.",
      "Designed 'thinking state' animations that maintained narrative immersion during processing.",
      "Personalized interaction pacing and conversation based on discussion with AI.",
      "Proved viability of 'Privacy-First' AI by processing all voice data locally (no cloud).",
      "Each experience was unique, with no two encounters alike based on visitor input, and take away physical mementos generated by AI character.",
    ],
    why: 'GenAI breaks immersion when latency is high. The challenge was designing a "Latency Masking" system that kept users engaged during the 3-second compute window of early LLMs. Making the AI feel human required more than just dialogue design — it demanded a holistic system that considered pacing, lighting, and physical space.',
    architectureDesc: "A local-first stack designed to process voice-to-voice interaction in under 200ms using a quantized Llama model running on my local MacBook Pro M3 Metal/GPU.",
    key_components: [
      'Full production design for Prof. Dupin’s office establishing world/story.',
      'Dialogue states changed with audio level triggers.',
      'System schematic (camera → STT → LLM → TTS → led lighting).',
      'Participant privacy agency to prevent responses to go to the cloud.',
      'Local LLM running on edge device for low latency.'
    ],
    designDesc: `Really there were two interfaces: 
    1. The operation of the audio/visual/AI experience.
    2. The live audio chat interface with the AI. 

    To mitigate the 'Uncanny Valley,' I designed the interface to be an invisible layer. Instead of a chat window, the UX relied on LED cues—lighting changes and subtle sound design—to signal the AI's 'listening' and 'thinking' states. This reduced the cognitive load of a standard conversational UI, allowing users to maintain eye contact with the physical avatar.

    The second interface (shown right) is the workspace I custom made to give me operational control of lights, computer vision inputs and outputs, inference, and audio (DAW). The left image is the prototype wireframe and the right is the final product UI.`,
    uxVisual: "/images/maia_ui.png",  
    featured: true,
    featuredVideo: '/video/teaser_MAIA_vertical.mp4',
    outcomesVisual: '/images/MAIA_outcomes.png',
    outcomesVisual2: '/images/MAIA_process.png',
    processVisual: '/images/MAIA_process.png',
    overviewVisual: '/images/MAIA_overview.png'
  },

  fairyland: {
    title: 'FAIRYLAND',
    subtitle: 'Multimodal Narrative System',
    link: 'https://fairylandshow.com/',
    img: '/images/fairyland.png',
    tags: ['Multimodal Systems', 'Web App', 'System Design', 'GenAI'],
    overview: `A living storyworld that connects audiences across live performance, web, film, and AI‑driven character encounters so engagement continues before, during, and after the show.`,
    role: `Head of Product UX, Designer, Creative Technologist & Full Stack Engineer — owned experience strategy across mediums, ticketing/onboarding UX, and cohesion between live and digital touchpoints.`,
    outcomes: [
      'Architected a "Story Operating System" that synchronized narrative state across live performance, web, and email, creating a persistent world for the audience.',
      'Designed a narrative-led ticketing flow that converted 20% of web visitors into registered users, and 66% of users into ticket purchasers.',
      'Reduced production fragmentation by building a shared "Story Bible" database that served as the single source of truth for design, dev, and performance teams.',
      'Extended the show’s lifecycle by 4 weeks through a pre-show digital onboarding experience that "primed" the audience before they entered the venue.'
    ],
    why: 'Engagement with live experiences often ends when the curtain falls. The challenge was designing a multimodal system that extended narrative immersion beyond the theater through web and AR.',
    architectureDesc: "A 'Story Operating System' that synchronizes user state across disjointed mediums. The architecture binds a Next.js web onboarding flow, Stripe ticketing API, and live venue entry systems into a single persistent user record, ensuring narrative choices made online trigger specific interactions in the physical venue.",
    key_components: [
      'Experience map linking live to digital follow‑ups.',
      'Ticketing & onboarding flows.',
      'AI chat UI tied to lore.',
      'AI-powered community engagement awareness',
    ],
    featured: true,
    designDesc: `Designing for narrative cohesion across mediums required a unified visual language and interaction patterns. I developed a modular UI system that adapted to both web and mobile contexts, ensuring users felt continuity whether they were engaging with the story online or in-person. The use of consistent typography, color schemes, and iconography reinforced brand identity while facilitating intuitive navigation through complex narrative layers.
    
    The ticketing flow was designed to be more than just a transaction; it was an entry point into the story. By integrating narrative elements into the purchase process, users were 'primed' for the experience ahead, increasing engagement and anticipation.
    
    The web onboarding experience served as a digital prologue, setting the stage for the live performance. Through interactive elements and character-driven content, users were immersed in the story world before stepping into the venue, enhancing overall engagement.
    
    Below is the profile UI that users interacted with during onboarding and post-show follow-ups. It was designed to be a central hub for narrative progression, allowing users to track their journey and access exclusive content tied to their in-show choices.`,
    uxVisual: "/images/FAIRYLAND_UI.png",
    outcomesVisual: '/images/FAIRYLAND_outcomes.png',
    outcomesVisual2: '/images/FAIRYLAND_outcomes2.png',
    processVisual: '/images/FAIRYLAND_process.png',
    overviewVisual: '/images/FAIRYLAND_overview.png'
  },

  chalknotes: {
    title: 'ChalkNotes',
    subtitle: 'Spatial Audio AR Platform',
    link: 'https://chalknotes.com/',
    img: '/images/chalknotes.png',
    tags: ['Spatial Audio', 'AR', 'Product Strategy', 'Mobile', 'No-Code Tools', "React Native", "Figma"],
    overview: `A mixed‑reality audio‑AR platform that lets creators drop stories onto real‑world maps and audiences discover them.`,
    role: `Lead Product Designer, UX Strategist, Engineer Manager. Owned end‑to‑end design across no‑code authoring and mobile discovery. Led research, prototyping, and usability testing with creators and audiences in uncontrolled real‑world environments.`,
    outcomes: [
      "Validated an 'Audio-First' AR interaction model, reducing screen-time during the experience by 60%.",
      "Shipped a 'No-Code' spatial authoring tool allowing creators to place audio without technical skills.",
      "Solved for GPS drift by designing broad 'Audio Geofences' rather than precise visual anchors.",
      "Delivered a seamless user experience that balanced engagement with safety in urban environments.",
      "Codified best practices for mixed‑reality experience design in open, unpredictable environments."
    ],
    why: "Visual AR demands too much attention. The business problem was creating a 'Heads-Up' engagement model that allowed users to consume content while navigating busy city streets.",   
    architectureDesc: "A geospatial audio engine that triggers sound based on GPS radius, utilizing a React Native frontend and a Firebase real-time backend for creator updates. A dual-client ecosystem: a React Native mobile app for geospatial discovery and a React web dashboard for creator administration. The system relies on Firebase NoSQL for real-time authentication and state sync, integrating a web3 'XP' gamification layer to drive physical foot traffic via tokenized collectibles.",
    key_components: [
      'Location-based audio triggers on mobile map.',
      "No-code web authoring tool for spatial story placement.",
      'Content discovery feed with experience previews.',
      'Community engagement features (sharing, reviews).'
    ],
    designDesc: `The core design challenge was 'Heads-Up' usability. I moved the primary interaction controls to the bottom third of the screen (thumb zone) and designed high-contrast, bold typography that remains legible in direct sunlight. The 'Audio Radar' visualization gave users directional feedback without requiring map literacy, solving the 'blue dot' anxiety common in GPS apps.
    
    Below is the augmented reality element activation. Instead of relying on visual markers alone, I designed an audio-centric interface where users hear spatial cues as they approach points of interest. The UI provides subtle visual feedback, but the primary interaction is auditory, allowing users to stay aware of their surroundings while engaging with content.`,
    uxVisual: "/images/tpm/chalknotes_ui_grid.png",
    outcomesVisual: '/images/tpm/chalknotes_outcomes.png',
    outcomesVisual2: '/images/tpm/chalknotes_outcomes2.png',
    processVisual: '/images/tpm/chalknotes_process.png',
    overviewVisual: '/images/tpm/chalknotes_overview.png',
    featured: true
  },

  esg_materiality: {
    title: 'ESG Materiality App',
    subtitle: 'B2B Data Visualization',
    img: '/images/esg.png',
    tags: ['B2B SaaS', 'Data Viz', 'Complex Workflows', 'Strategy'],
    overview: `A massive multi-featured business intelligence web app to capture, prioritize, and aggregate ESG topics for the Global 500, modeling enterprise value and environmental impact of today and trajectories over the next decade.`,
    role: `Lead Product/UX — research synthesis, information architecture, dashboards, and scenario modeling UX.`,
    outcomes: [
      "Productized a manual consulting service, creating a product that naturalized internal data.",
      "Unified 5+ disparate data streams into a single 'Materiality Matrix' dashboard.",
      "Reduced stakeholder reporting time by ~40% through automated visualization.",
      "Future proofed the platform for evolving ESG standards and reporting requirements.",
      "Facilitated cross-functional workshops to align on ESG priorities and data strategies.",
      "Created War games scenarios to model long-term impact of ESG strategies."
    ],
    architectureDesc: "A B2B SaaS architecture transforming unstructured qualitative survey data into a structured SQL schema and quant reporting. The frontend utilizes complex D3.js visualization libraries to render dynamic 'Materiality Matrices,' allowing strategy teams to model risk trajectories in real-time rather than relying on static key_components.",
    why: "Consulting data is often trapped in static PDFs. The challenge was transforming abstract strategy frameworks into a dynamic product used by Global 500 that allowed for year-over-year modeling and aggregation of ESG data.",
    key_components: [
      'Materiality topic priority system with unified taxonomy.',
      'New insights and trend discovery from multi-project data aggregation.',
      'Global 500 Executive dashboard protected by role-based access controls.',
      'Topic, Interview & Survey scoring, ingestion and scheduling.',
    ],
    designDesc: "I replaced static tabular data with a dynamic interactive scatter plot. The UX allows users to drag-and-drop 'topics' to reweight their priority, giving strategy teams a tactile way to model 'What-If' scenarios. I designed a rigid grid system to ensure that even when displaying 50+ data points, the dashboard remained scannable and never felt cluttered.",
    uxVisual: "/images/esg_ui.png",
    featuredVideo: '/video/esg_video.mp4',
    outcomesVisual: '/images/esg_outcomes.png',
    outcomesVisual2: '/images/esg_outcomes2.png',
    processVisual: '/images/esg_process.png',
    overviewVisual: '/images/esg_overview.png',
    featured: true
  },

  emily_was_here: {
    title: 'Emily Was Here — Brooklyn Bridge Experience',
    subtitle: 'Geospatial Mixed Reality',
    link: 'https://brooklynbridgeexperience.com/',
    img: '/images/emily.png',
    tags: ['Geospatial', 'Audio AR', 'UX Research', 'Mobile'],
    overview: `A poetic, GPS‑triggered audio walk across the Brooklyn Bridge. Voiceover, poetry, and ambient sound transform the crossing into an intimate narrative.`,
    role: `XR Experience Designer & Technical Director — route design, GPS trigger pacing, and sound layering using the ChalkNotes stack.`,
    architectureDesc: "A geospatial audio engine that triggers sound based on GPS radius, utilizing a React Native frontend and a Firebase real-time backend for creator updates.",
    outcomes: [
      'Shipped an on‑demand, location‑locked experience with no live performers or on‑site staff.',
      'Demonstrated emotional impact through sound‑first design, measured through qualitative feedback and replays.',
      'Extended the ChalkNotes architecture for more precise environmental and route control.',
      'Managed team of 20 actors to produce high-quality voiceover recordings.'
    ],
    why: `Explores low‑friction, site‑specific storytelling that scales to city landmarks without heavy reliance on the device in the user's hand.`,
    key_components: [
      'GPS‑triggered audio walk route.',
      'Narrative script and voiceover recordings.',
      'Ambient soundscapes layered for immersion.',
      'Route pacing and trigger radius design.'
    ],
    designDesc: `The landing page was to built excitement for the experience and be a web purchasing experience integrated with the mobile app. 
    
    The app experience was built on my app Chalknotes. I had to improve the app for this custom experience that lasted 2 hours. Designing for a seamless audio walk required careful consideration of pacing and environmental context. I mapped the route to identify natural pauses and scenic viewpoints, ensuring that audio triggers aligned with moments of visual interest. The UX prioritized minimal screen interaction, allowing users to focus on the auditory experience while navigating the bridge safely.
    `,
    uxVisual: "/images/bridge_ui.png",
    outcomesVisual: '/images/bridge_outcomes.png',
    outcomesVisual2: '/images/bridge_outcomes2.png',
    processVisual: '/images/bridge_process.png',
    overviewVisual: '/images/bridge_overview.png',
    featured: false
  },

  // --- Additional portfolio projects (site) ---
  juliet_wherefore: {
    title: 'Wherefore Art Thou, Juliet?',
    link: 'https://storyversenyc.com/',
    img: '/images/juliet.png',
    tags: ['XR', 'Location‑based', 'Audio',],
    overview: `A choose‑your‑own‑adventure mixed‑reality journey across NYC’s Theater District, guided by interviews with Broadway performers.`,
    role: `Experience Designer — route/stop design, narrative framing, and mobile listening UX.`,
    outcomes: [
      'Piloted narrative traversal across multiple neighborhood stops.',
      'Prototyped creator‑led location authoring patterns.',
      'Documented accessibility and safety considerations for street‑level play.'
    ],
    why: `Tests scalable patterns for cultural‑district storytelling that can be authored by small teams.`,
    key_components: [
      'Route map and stop list.',
      'Interview‑driven script fragments.',
      'Street‑level interaction captures.',
      'Authoring UI frames.'
    ],
    featured: false
  },



internal_ops_ford: {
    title: 'Internal Ops UX — Ford Foundation',
    subtitle: 'Enterprise Knowledge Discovery',
    img: '/images/ford_ops.png',
    tags: ['NLP', 'Semantic Search', 'Information Architecture', 'Enterprise BI'],
    overview: `Modernizing institutional memory. A UX transformation of an 80-year grantmaking archive, applying NLP to turn millions of static documents into a discoverable knowledge engine.`,
    role: `Lead UX & Research — stakeholder interviews, taxonomy design, search UX, and legacy migration strategy.`,
    why: "Institutional knowledge was trapped in siloed legacy repositories. The challenge was preventing 'organizational amnesia' by transforming 80 years of unstructured PDFs and grant letters into a searchable, semantic database without overwhelming non-technical Program Officers.", 
    outcomes: [
      'Consolidated 4 disparate legacy repositories into a Single Source of Truth for grant history.',
      'Reduced document retrieval time for Program Officers by introducing NLP-driven semantic facets.',
      'Recovered "lost" institutional knowledge by digitizing and tagging 80 years of physical and digital artifacts.',
      'Brought about cross-departmental alignment on knowledge management best practices.'
    ],
    architectureDesc: "A unified knowledge retrieval architecture. We consolidated disparate SQL databases and file servers into a single search index. The pipeline utilized NLP entity extraction to automatically tag documents with 'about-ness' (themes, regions, demographics), enabling semantic retrieval across decades of unstructured text.",
    designDesc: "Designing for 'Sense-Making,' not just search. I moved beyond simple keyword matching to design a faceted discovery interface. The UX introduced 'Topic Clusters' and 'Smart Filters' that allowed officers to drill down by era, grant type, or impact region, reducing the cognitive load of sifting through legal archives.",
    uxVisual: '/images/ford_ops.png', 
    processVisual: '/images/ford_ops_process.png',
    key_components: [
      'Taxonomy & Metadata Schema',
      'Entity Extraction Logic',
      'Intranet/SharePoint as Semantic Search Frontend',
      'Grantmaking data ingestion pipeline'
    ],
    
    featured: false
  },

    // --- Grad portfolio (playful experiments & R&D) ---
  grad_labs: {
    title: 'Creative Labs',
    img: '/images/creative_labs.png',
    tags: ['Interactive', 'Light', 'Installation', 'Play'],
    overview: `A series of experimental installations exploring light, space, and interaction design through playful systems at NYU.`,
    role: `Designer & Engineer — ideation, prototyping, fabrication, and interaction design for physical installations.`,
    outcomes: [
      'Developed multiple interactive light installations using projection mapping and LED technologies.',
      'Explored user interaction patterns through light and spatial design.',
      'Documented installation processes and user engagement.'
    ],
    why: `Investigates the intersection of light, space, and user interaction through hands-on experimentation.`,
    key_components: ['Installation photos', 'Projection mapping tests', 'Interaction diagrams', 'User engagement captures'
    ],
    featured: false
  },
};

export const allTags = Array.from(new Set(Object.values(projects).flatMap(p => p.tags))).sort();
